import { useState } from 'react'
import { verifyPassword, setAdminAuth, checkAdminAuth } from '@/utils/adminAuth'
import { useConfiguratorStore } from '@/store/configuratorStore'
import { useUIStore } from '@/store/uiStore'
import { MODULES } from '@/data/modules'
import { Button } from '@/components/ui/Button'
import { formatINR } from '@/utils/formatCurrency'
import { Lock, LogOut } from 'lucide-react'
import { clsx } from 'clsx'

export const AdminPanel = () => {
  const [isAuthed, setIsAuthed] = useState(checkAdminAuth())
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const { customPrices, setCustomPrice, resetCustomPrice } = useConfiguratorStore()
  const { addToast } = useUIStore()

  const handleLogin = () => {
    if (verifyPassword(password)) {
      setAdminAuth(true)
      setIsAuthed(true)
      setError('')
    } else {
      setError('Incorrect password')
    }
  }

  const handleLogout = () => {
    setAdminAuth(false)
    setIsAuthed(false)
  }

  if (!isAuthed) {
    return (
      <div className="min-h-screen bg-dark-base flex items-center justify-center p-4">
        <div className="bg-dark-card border border-dark-border rounded-xl p-8 w-full max-w-sm">
          <div className="text-center mb-6">
            <Lock className="w-10 h-10 text-sage mx-auto mb-3" />
            <h1 className="font-display text-2xl text-white">Admin Panel</h1>
            <p className="text-sm text-gray-500 mt-1">Enter the admin password to continue</p>
          </div>
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleLogin()}
            placeholder="Password"
            className="w-full bg-dark-base border border-dark-border rounded-lg px-4 py-2.5 text-white text-sm mb-3 focus:outline-none focus:border-sage"
            aria-label="Admin password"
          />
          {error && <p className="text-red-400 text-xs mb-3">{error}</p>}
          <Button fullWidth onClick={handleLogin}>Login</Button>
        </div>
      </div>
    )
  }

  const handleExport = () => {
    const updated = MODULES.map(m => ({
      ...m,
      oneTime: customPrices[m.id] ?? m.oneTime,
    }))
    const snippet = `// Generated by Sage Tech Admin Panel — ${new Date().toLocaleDateString()}\n// Paste this into src/data/modules.ts to make pricing permanent\n\nexport const MODULES: Module[] = ${JSON.stringify(updated, null, 2)}`
    navigator.clipboard.writeText(snippet).then(() => {
      addToast({ type: 'success', message: 'Copied to clipboard. Paste into src/data/modules.ts' })
    })
  }

  return (
    <div className="min-h-screen bg-dark-base pt-20 pb-12 px-4">
      <div className="max-w-6xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="font-display text-2xl text-white">Module Pricing Editor</h1>
            <p className="text-sm text-gray-500 mt-1">Changes saved here persist for this browser session only.</p>
          </div>
          <div className="flex gap-3">
            <Button variant="secondary" onClick={handleExport}>Export as TypeScript</Button>
            <Button variant="ghost" onClick={handleLogout}><LogOut className="w-4 h-4" /> Logout</Button>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-dark-border text-gray-500 text-xs uppercase tracking-wider">
                <th className="text-left py-3 px-3">Module</th>
                <th className="text-left py-3 px-3">Category</th>
                <th className="text-right py-3 px-3">Base Price (₹)</th>
                <th className="text-right py-3 px-3">Current Price (₹)</th>
                <th className="text-center py-3 px-3">Actions</th>
              </tr>
            </thead>
            <tbody>
              {MODULES.map(m => {
                const isModified = customPrices[m.id] !== undefined
                const currentPrice = customPrices[m.id] ?? m.oneTime
                return (
                  <tr key={m.id} className="border-b border-dark-border/50 hover:bg-dark-hover/50">
                    <td className="py-3 px-3">
                      <div className="flex items-center gap-2">
                        {isModified && <span className="w-2 h-2 rounded-full bg-orange-400" title="Modified" />}
                        <span className="text-white font-medium">{m.name}</span>
                      </div>
                    </td>
                    <td className="py-3 px-3 text-gray-500 capitalize">{m.category}</td>
                    <td className="py-3 px-3 text-right font-mono text-gray-500">{formatINR(m.oneTime)}</td>
                    <td className="py-3 px-3 text-right">
                      <input
                        type="number"
                        value={currentPrice}
                        onChange={e => setCustomPrice(m.id, Number(e.target.value))}
                        className={clsx(
                          'w-32 bg-dark-base border rounded px-2 py-1 text-right font-mono text-sm focus:outline-none focus:border-sage',
                          isModified ? 'border-orange-400/50 text-orange-300' : 'border-dark-border text-white',
                        )}
                        aria-label={`Price for ${m.name}`}
                      />
                    </td>
                    <td className="py-3 px-3 text-center">
                      {isModified && (
                        <button
                          className="text-xs text-gray-500 hover:text-white"
                          onClick={() => resetCustomPrice(m.id)}
                        >
                          Reset
                        </button>
                      )}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
